<a href="https://colab.research.google.com/github/WizardsugarGG/MINERIA-DE-DATOS/blob/main/chi-cuadradp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1:
En una encuesta realizada en dos ciudades (Ciudad A y Ciudad B), se preguntó a los habitantes cuál era su medio de transporte preferido: automóvil o transporte público.

Los resultados fueron:
               Automóvil    Transporte Público
Ciudad A    85    65
Ciudad B    50    100

¿Existe una relación significativa entre la ciudad de residencia y la preferencia de transporte? Usa:
𝛼 = 0.05


In [1]:
import pandas as pd
import numpy as np
from scipy import stats

# Datos observados en forma de tabla de contingencia
tabla = np.array([[85, 65],
                  [50, 100]])

# Crear un DataFrame para visualizar mejor
df = pd.DataFrame(tabla,
                  index=["Ciudad A", "Ciudad B"],
                  columns=["Automóvil", "Transporte Público"])

print("Tabla de contingencia:")
print(df)

# Prueba Chi-cuadrado de independencia
chi2, p, dof, expected = stats.chi2_contingency(tabla)

print("\nResultados de la prueba Chi-cuadrado:")
print(f"Chi2 = {chi2:.2f}")
print(f"p-valor = {p:.4f}")
print(f"Grados de libertad = {dof}")
print("Frecuencias esperadas:")
print(expected)

# Conclusión
alpha = 0.05
if p < alpha:
    print("\nConclusión: Se rechaza H0. Existe relación significativa entre ciudad y preferencia de transporte.")
else:
    print("\nConclusión: No se rechaza H0. No hay evidencia de relación significativa.")


Tabla de contingencia:
          Automóvil  Transporte Público
Ciudad A         85                  65
Ciudad B         50                 100

Resultados de la prueba Chi-cuadrado:
Chi2 = 15.57
p-valor = 0.0001
Grados de libertad = 1
Frecuencias esperadas:
[[67.5 82.5]
 [67.5 82.5]]

Conclusión: Se rechaza H0. Existe relación significativa entre ciudad y preferencia de transporte.


Ejercicio 2: Un investigador de salud pública quiere saber si el nivel educativo influye en el consumo de tabaco. Encuesta a 200 personas y obtiene: Fuma    No Fuma Sin estudios    40    20 Bachillerato    35    45 Universidad    15    45 en python



In [2]:
import pandas as pd
import numpy as np
from scipy import stats

# Datos observados en forma de tabla de contingencia
tabla = np.array([[40, 20],   # Sin estudios
                  [35, 45],   # Bachillerato
                  [15, 45]])  # Universidad

# Crear un DataFrame para visualizar mejor
df = pd.DataFrame(tabla,
                  index=["Sin estudios", "Bachillerato", "Universidad"],
                  columns=["Fuma", "No Fuma"])

print("Tabla de contingencia:")
print(df)

# Prueba Chi-cuadrado de independencia
chi2, p, dof, expected = stats.chi2_contingency(tabla)

print("\nResultados de la prueba Chi-cuadrado:")
print(f"Chi2 = {chi2:.2f}")
print(f"p-valor = {p:.4f}")
print(f"Grados de libertad = {dof}")
print("Frecuencias esperadas:")
print(expected)

# Conclusión
alpha = 0.05
if p < alpha:
    print("\nConclusión: Se rechaza H0. Existe relación significativa entre nivel educativo y consumo de tabaco.")
else:
    print("\nConclusión: No se rechaza H0. No hay evidencia de relación significativa.")

Tabla de contingencia:
              Fuma  No Fuma
Sin estudios    40       20
Bachillerato    35       45
Universidad     15       45

Resultados de la prueba Chi-cuadrado:
Chi2 = 21.13
p-valor = 0.0000
Grados de libertad = 2
Frecuencias esperadas:
[[27. 33.]
 [36. 44.]
 [27. 33.]]

Conclusión: Se rechaza H0. Existe relación significativa entre nivel educativo y consumo de tabaco.


Ejercicio 3:
Un nutriólogo quiere saber si el tipo de dieta que sigue una persona está relacionado con su nivel de colesterol. Evalúa a 180 pacientes y registra:

                         Colesterol Alto    Colesterol Normal
Dieta vegana    10    50
Dieta mixta    30    40
Dieta carnívora    45    5
¿Existe relación entre el tipo de dieta y el nivel de colesterol? Usa
𝛼 = 0.05

In [3]:
import pandas as pd
import numpy as np
from scipy import stats

# Datos observados en forma de tabla de contingencia
tabla = np.array([[10, 50],   # Dieta vegana
                  [30, 40],   # Dieta mixta
                  [45, 5]])   # Dieta carnívora

# Crear un DataFrame para visualizar mejor
df = pd.DataFrame(tabla,
                  index=["Vegana", "Mixta", "Carnívora"],
                  columns=["Colesterol Alto", "Colesterol Normal"])

print("Tabla de contingencia:")
print(df)

# Prueba Chi-cuadrado de independencia
chi2, p, dof, expected = stats.chi2_contingency(tabla)

print("\nResultados de la prueba Chi-cuadrado:")
print(f"Chi2 = {chi2:.2f}")
print(f"p-valor = {p:.6f}")
print(f"Grados de libertad = {dof}")
print("Frecuencias esperadas:")
print(expected)

# Conclusión
alpha = 0.05
if p < alpha:
    print("\nConclusión: Se rechaza H0. Existe relación significativa entre tipo de dieta y nivel de colesterol.")
else:
    print("\nConclusión: No se rechaza H0. No hay evidencia de relación significativa.")

Tabla de contingencia:
           Colesterol Alto  Colesterol Normal
Vegana                  10                 50
Mixta                   30                 40
Carnívora               45                  5

Resultados de la prueba Chi-cuadrado:
Chi2 = 59.72
p-valor = 0.000000
Grados de libertad = 2
Frecuencias esperadas:
[[28.33333333 31.66666667]
 [33.05555556 36.94444444]
 [23.61111111 26.38888889]]

Conclusión: Se rechaza H0. Existe relación significativa entre tipo de dieta y nivel de colesterol.
