<a href="https://colab.research.google.com/github/WizardsugarGG/MINERIA-DE-DATOS/blob/main/numpyEjercios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from numpy import random

In [4]:
#tipos de array
array_0 = np.array(42)
print(array_0)

array_1 = np.array([1,2,3,4,5])
print(array_1)

array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [7]:
#index de los arrays
print(array_1[0])
print(array_2[1][1]) #fila columna
print(array_3[1,0,0]) #dim de fila columna

1
5


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [8]:
#shape
print(array_1.shape)
print(array_2.shape)
print(array_3.shape)


(5,)
(2, 3)
(3, 3)


In [10]:
#reshape
print(array_3.reshape(1,9))
print(array_3.reshape(9,1))


[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [15]:
#concatenation
print(np.concatenate((array_1,array_2)))

#split
print(np.array_split(array_1,1))




ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [20]:
#where
print(np.where(array_1 == 3))

#ordenar
arrayN = np.array([3,2,0,1])
print(np.sort(arraN))

print(np.sort(arrayN)[::-1])

(array([2]),)
[0 1 2 3]
[3 2 1 0]


In [22]:
#RANDOM
numero = random.randint(100,200,1)#(inicio,fin.num elemto)
#print(numero)

numero = random.rand(10 , size[5])
#print(numero)

numero =random.randint(10 , size=[2,3])
print(numero)



[[6 0 2]
 [9 4 4]]


In [25]:
#numeros decimal
numero = random.rand()
print(round(numero,2))

numero2 = random.rand()+5
print(numero2)

numero3 = random.rand(3,5)
print(numero3)

#lista de nombres

lista_nombres = ["juan","pedro","maria"]
print(random.choice(lista_nombres))


0.3


ejercios

Crea un array de 10 números aleatorios enteros entre 0 y 100.
Crea un array de 5 números aleatorios decimales entre 0 y 1.
Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.
Crea un array de 10 números aleatorios enteros y sepáralo en dos arrays de 5 elementos cada uno.
Crea una matriz de 3x3 con números aleatorios decimales entre 0 y 1.
Crea un array de 10 números aleatorios enteros y selecciona 3 elementos al azar.
Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.

In [26]:
# 1. Crear un array de 10 números aleatorios enteros entre 0 y 100
array1 = np.random.randint(0, 101, 10)
print("Array 10 enteros:", array1)

Array 10 enteros: [ 48  28   6   6 100  18  44  79  97  50]


In [27]:
# 2. Crear un array de 5 números aleatorios decimales entre 0 y 1
array2 = np.random.rand(5)
print("Array 5 decimales:", array2)

Array 5 decimales: [0.83020648 0.82587282 0.66727882 0.02938765 0.69189897]


In [28]:
# 3. Crear dos arrays de números aleatorios enteros de longitud 5 y concatenarlos
a = np.random.randint(0, 100, 5)
b = np.random.randint(0, 100, 5)
concatenado = np.concatenate((a, b))
print("Array A:", a)
print("Array B:", b)
print("Concatenado:", concatenado)

Array A: [77 23 82 61  8]
Array B: [ 0 94 30 94 14]
Concatenado: [77 23 82 61  8  0 94 30 94 14]


In [29]:
# 4. Crear un array de 10 números aleatorios enteros y separarlo en dos arrays de 5
array3 = np.random.randint(0, 100, 10)
parte1, parte2 = np.split(array3, 2)
print("Array original:", array3)
print("Parte 1:", parte1)
print("Parte 2:", parte2)

Array original: [75 70 79 92 59 42 32 51  9 88]
Parte 1: [75 70 79 92 59]
Parte 2: [42 32 51  9 88]


In [30]:
# 5. Crear una matriz 3x3 con números aleatorios decimales entre 0 y 1
matriz = np.random.rand(3, 3)
print("Matriz 3x3:\n", matriz)


Matriz 3x3:
 [[0.18241151 0.78374158 0.20709895]
 [0.16000121 0.50359966 0.75190276]
 [0.23101568 0.23785155 0.76072722]]


In [31]:
# 6. Crear un array de 10 números aleatorios enteros y seleccionar 3 al azar
array4 = np.random.randint(0, 100, 10)
seleccion = np.random.choice(array4, 3, replace=False)
print("Array:", array4)
print("3 elementos al azar:", seleccion)


Array: [11 46 47 82 87 20 34 11 25 17]
3 elementos al azar: [11 25 87]


In [32]:
# 7. Crear un array de 10 números aleatorios enteros entre 0 y 100 y calcular la media
array5 = np.random.randint(0, 101, 10)
media = np.mean(array5)
print("Array:", array5)
print("Media:", media)

Array: [80 74 88 93 58 43 39 58 32 65]
Media: 63.0
