<a href="https://colab.research.google.com/github/WizardsugarGG/MINERIA-DE-DATOS/blob/main/teorema%20de%20bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import pandas as pd

data={
    'correo': [
        "gana dinero rapido",
        "oferta exclusiva gratis",
        "reunion mañana ",
        "gana premio gratis"
    ],
    'clase' : [
        "spam",
        "spam",
        "no_spam",
        "no_spam"
    ]
}

df = pd.DataFrame(data)
print(df)

#convertir el texto en una matriz de caracteristicas
vectorizador = CountVectorizer()
x = vectorizador.fit_transform(df['correo'])
print(x.toarray())

                    correo    clase
0       gana dinero rapido     spam
1  oferta exclusiva gratis     spam
2          reunion mañana   no_spam
3       gana premio gratis  no_spam
[[1 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 1]
 [0 0 1 1 0 0 1 0 0]]


In [12]:
#varible objetivo

y = df['clase']

#entrenar modelo
modelo = MultinomialNB() #sepacion de datos
modelo.fit(x,y) # entrena por separado


#Predecir la clase de nuevo correo
nuevo_correo = ["oferta gratis"]
correo_vectorizado = vectorizador.transform(nuevo_correo)
prediccion = modelo.predict(correo_vectorizado)
print(prediccion)

['spam']


In [14]:
palabras = vectorizador.get_feature_names_out()
tabla_prob = pd.DataFrame(
    modelo.feature_log_prob_,
    columns=palabras,
    index=modelo.classes_
)
print(tabla_prob)

           dinero  exclusiva      gana    gratis   mañana    oferta   premio  \
no_spam -2.639057  -2.639057 -1.945910 -1.945910 -1.94591 -2.639057 -1.94591   
spam    -2.014903  -2.014903 -2.014903 -2.014903 -2.70805 -2.014903 -2.70805   

           rapido  reunion  
no_spam -2.639057 -1.94591  
spam    -2.014903 -2.70805  


In [ ]:
palabras = vectorizer.get_feature_names_out()
tabla_prob = pd.DataFrame(modelo.feature_log_prob_, columns=palabras,index=modelo.classes_)

TEOREMA DE BAYES (NAIVE BAYES)


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import pandas as pd

data ={
    "reseña":[
          "el producto funciona excelente",
        "muy buena calidad",
        "el producto llegó dañado",
        "muy mala calidad",
        "excelente producto y calidad"
    ],
    "clasificacion":[
            "satisfecho",
        "satisfecho",
        "insatisfecho",
        "insatisfecho",
        "satisfecho"
    ]

}
df = pd.DataFrame(data)


In [6]:
#vectorizacion del texto
# Re-create df and y for sentiment analysis to ensure correct data is used
data_sentiment = {
    "reseña":[
          "el producto funciona excelente",
        "muy buena calidad",
        "el producto llegó dañado",
        "muy mala calidad",
        "excelente producto y calidad"
    ],
    "clasificacion":[
            "satisfecho",
        "satisfecho",
        "insatisfecho",
        "insatisfecho",
        "satisfecho"
    ]
}
df_sentiment = pd.DataFrame(data_sentiment)

vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df_sentiment['reseña'])
print(x.toarray())

# Define the target variable 'y' from the sentiment analysis DataFrame
y = df_sentiment['clasificacion']

#entrenar modelo
modelo = MultinomialNB() #sepacion de datos
modelo.fit(x,y) # entrena por separado
# Comentario nuevo
nuevo = ["producto mala calidad"]
X_new = vectorizer.transform(nuevo)

# Predicción
prediccion = modelo.predict(X_new) # Corrected 'model' to 'modelo'
probabilidades = modelo.predict_proba(X_new) # Corrected 'model' to 'modelo'

print("Comentario:", nuevo[0])
print("Clasificación predicha:", prediccion[0])
print("Probabilidades:", probabilidades)

[[0 0 0 1 1 1 0 0 0 1]
 [1 1 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1 1 0]
 [0 1 0 0 1 0 0 0 0 1]]
Comentario: producto mala calidad
Clasificación predicha: satisfecho
Probabilidades: [[0.49107811 0.50892189]]
